image: python:3.7-alpine

variables:
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .pip

before_script:
  - python3 -V                           # Print out python version for debugging
  - mkdir -p .pip
  - python3 -m pip install -U pip
  - pip --cache-dir=.pip install -r requirements.txt

build:
  stage: build
  script:
  - python3 ./app.py
