language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - pytest
  - pytest --cov=./
after_success:
- codecov # It uses the CODECOV_TOKEN environment variable
